# Generated by Django 5.1.6 on 2025-04-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('resim', models.ImageField(upload_to='projeler/')),
            ],
        ),
    ]
