# Generated by Django 5.1.6 on 2025-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_projeler_kategori_sertifika_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeler',
            name='kategori',
        ),
    ]
