# Generated by Django 5.1.6 on 2025-04-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_projeler_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='projeler/resimler/')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proje_resimleri', to='pages.projeler')),
            ],
        ),
        migrations.AddField(
            model_name='projeler',
            name='resimler',
            field=models.ManyToManyField(blank=True, related_name='projeler_resimleri', to='pages.projeresmi'),
        ),
    ]
