# Generated by Django 5.1.6 on 2025-04-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_projeresmi_projeler_resimler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeler',
            name='resimler',
        ),
    ]
