# Generated by Django 5.1.6 on 2025-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_projeler_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeler',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
    ]
