# Generated by Django 5.1.6 on 2025-04-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_mesaj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projeler',
            new_name='Proje',
        ),
    ]
