# Generated by Django 5.1.6 on 2025-04-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_projeler_proje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proje',
            new_name='Projeler',
        ),
    ]
