# Generated by Django 5.1.6 on 2025-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_proje_projeler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifika',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='sertifikalar/'),
        ),
    ]
