# Generated by Django 5.1.6 on 2025-04-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sertifika_dosya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertifika',
            name='dosya',
        ),
    ]
