# Generated by Django 5.1.6 on 2025-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_sertifika_kategoriler_sertifika_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='SILA NUR TEZCAN', max_length=200)),
                ('aciklama', models.TextField()),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cv_dosyalar/')),
            ],
        ),
    ]
