# Generated by Django 5.1.6 on 2025-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_hakkimda'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='site_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeler',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projeler/videolar/'),
        ),
    ]
